name: Artifact_Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job_1: 
    name: Upload 2KB File to Artifact
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create 2KB File
        shell: bash
        run: |
          dd if=/dev/urandom of=2k_random.dat bs=2k count=1024
      - name: upload-artifact Action
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: 2k_random.dat

      - name: Display structure of downloaded file
        working-directory: homework


