
name: M9-LongTerm_PSD_Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  longterm_test:
    runs-on: PSD
    timeout-minutes: 1440
    steps:
    
    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Build Setup
      working-directory: ${{github.workspace}}
      run: | 
        chmod +x .github/workflows/script/build_setup.sh
        .github/workflows/script/build_setup.sh -t PM -r ${{github.sha}} -d ${{github.workspace}}

    - name: Long Term VM Test
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/longterm.sh
        .github/workflows/script/longterm.sh ${{github.workspace}}

    - name: Clean Backup Script
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/clean_backup.sh
        .github/workflows/script/clean_backup.sh -i "127.0.0.1" -p "M9-LongTerm_PM1_VM_Test" -n "longterm_pm" -r ${{github.sha}} -d ${{github.workspace}}